version: "3.9"

services:

  db:
    image: mysql:8.0
    container_name: ilpea_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: ilpea_db
      MYSQL_USER: ilpea_user
      MYSQL_PASSWORD: ilpea_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./ilpea-backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: ./ilpea-backend
    container_name: ilpea_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ilpea_user
      DB_PASSWORD: ilpea_pass
      DB_NAME: ilpea_db
      JWT_SECRET: linceHackatec2026_secret_key_ilpea
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy

    # 🔥 HOT RELOAD
    volumes:
      - ./ilpea-backend:/app
      - /app/node_modules

    command: npm run dev

  web:
    build: ./ilpea-frontend
    container_name: ilpea_web
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      API_URL: http://api:3000/api
    depends_on:
      - api

    # 🔥 HOT RELOAD
    volumes:
      - ./ilpea-frontend:/app

    command: npm run dev

volumes:
  db_data: